### ISSUE TITLE
No longer works? 

### ISSUE THREAD

**Issue by filoxo** [fcoury/node-anne-pro#1]
I seem to be unable to get this project to install. 

### System info

Mac OS 10.13.4 
node -v: v8.11.1
npm -v: 5.6.0

I also attempted using a later version of node 

node -v: v9.10.1
npm -v: 5.6.0

I see this error when attempting to install globally (`npm i -g anne-pro`)

<details>

```
➜  ~ npm i -g anne-pro

> ref@1.1.3 install /Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/anne-pro/node_modules/nodobjc/node_modules/ref
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:619:11: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<v8::String>("endianness").ToLocalChecked(), ...
          ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3164:3: note: 'ForceSet' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8config.h:321:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:619:131: error: no viable conversion from
      'v8::PropertyAttribute' to 'Local<v8::Value>'
  ...static_cast<PropertyAttribute>(ReadOnly|DontDelete));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &'
      for 1st argument
class Local {
      ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for
      1st argument
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:202:13: note: candidate
      template ignored: could not match 'Local<type-parameter-0-0>' against
      'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3166:51: note: passing argument
      to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/binding.cc:620:11: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNu...
          ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3164:3: note: 'ForceSet' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8config.h:321:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:620:86: error: no viable conversion from
      'v8::PropertyAttribute' to 'Local<v8::Value>'
  ...WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &'
      for 1st argument
class Local {
      ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for
      1st argument
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:202:13: note: candidate
      template ignored: could not match 'Local<type-parameter-0-0>' against
      'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3166:51: note: passing argument
      to parameter 'value' here
                                     Local<Value> value,
                                                  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:209:5: error: assigning to
      'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:163:39: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../src/binding.cc:619:20: note: in instantiation of function template
      specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
  target->ForceSet(Nan::New<v8::String>("endianness").ToLocalChecked(), ...
                   ^
2 warnings and 3 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/carlos/.nvm/versions/node/v9.10.1/bin/node" "/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/anne-pro/node_modules/nodobjc/node_modules/ref
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlos/.npm/_logs/2018-04-10T18_39_51_879Z-debug.log
➜  ~ 
```
</details>

I have CommandLineTools installed just fine. I also cloned the project and `npm install` locally in an attempt to `npm link` it manually, but received similar build failures as above.

<details>

```
➜  node-anne-pro git:(master) yarn install 
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/3] ⠐ ref:                                        ^
[2/3] ⠐ ref: not ok
[-/3] ⠐ waiting...
[-/3] ⠐ waiting...
error An unexpected error occurred: "/Users/carlos/dev/node-anne-pro/node_modules/nodobjc/node_modules/ref: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/carlos/dev/node-anne-pro/node_modules/nodobjc/node_modules/ref
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.10.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/carlos/dev/node-anne-pro/node_modules/nodobjc/node_modules/ref/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/carlos/.node-gyp/9.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/carlos/.node-gyp/9.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/carlos/.node-gyp/9.10.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/carlos/dev/node-anne-pro/node_modules/nodobjc/node_modules/ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:619:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<v8::String>(\"endianness\").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use CreateDataProperty / DefineOwnProperty\",
  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:619:131: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<v8::String>(\"endianness\").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/binding.cc:620:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<v8::String>(\"NULL\").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use CreateDataProperty / DefineOwnProperty\",
  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/binding.cc:620:86: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<v8::String>(\"NULL\").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:209:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/carlos/.node-gyp/9.10.1/include/node/v8.h:163:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \\
                                      ^~~~~~~~~~~~~~~~~~
../src/binding.cc:619:20: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
  target->ForceSet(Nan::New<v8::String>(\"endianness\").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                   ^
2 warnings and 3 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command \"/Users/carlos/.nvm/versions/node/v9.10.1/bin/node\" \"/Users/carlos/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/carlos/dev/node-anne-pro/node_modules/nodobjc/node_modules/ref
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok".
```

</details>

Any thoughts on what the issue may be? Thanks in advance!

**Comment by lewisvrobinson** [comment]
I'm having similar issues. Looks like there's a version mismatch somewhere down the dependancy tree that's causing some issues with the v8 bindings? But I'm guessing really... Perhaps running an older node version will fix it? Would love to see this project up an running again!

**Comment by filoxo** [comment]
Based on a lack of updates and a lack of response, this project is probably dead. Closing.
